# Generated by Django 4.2.29 on 2026-04-01 05:31

import apps.challenges.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_admin_tasks_and_submissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='admintasksubmission',
            name='attachment',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=apps.challenges.models.admin_task_submission_upload_to),
        ),
    ]
