# Generated by Django 4.2.29 on 2026-04-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0007_backfill_submission_elapsed_from_task_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedchallenge',
            name='device_batch_device_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
    ]
