# Generated by Django 4.2.29 on 2026-04-01 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenges', '0008_device_batch_device_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAgentDailyQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_date', models.DateField(db_index=True)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_agent_quotes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_useragentdailyquote',
                'ordering': ['-quote_date'],
            },
        ),
        migrations.CreateModel(
            name='SyndicateUserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='syndicate_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_syndicateuserprogress',
            },
        ),
        migrations.AddConstraint(
            model_name='useragentdailyquote',
            constraint=models.UniqueConstraint(fields=('user', 'quote_date'), name='uniq_user_agent_quote_per_day'),
        ),
    ]
